# nodeLinker: pnp
nodeLinker: node-modules

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.3.1.cjs

packageExtensions:
  "@types/react-dom@*":
    peerDependencies:
      "react": "*"
  "debug@*":
    peerDependencies:
      "supports-color": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      "typescript": "*"
