name: Deploy to S3

on:
  push:
    branches:
      - prod/js-sdk # prod/js-sdk 브랜치에 push될 때 트리거됩니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install
        working-directory: apps/js-sdk

      - name: Build project
        run: yarn build:prod
        working-directory: apps/js-sdk

      - name: Set VERSION environment variable
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        working-directory: apps/js-sdk

      - name: Sync files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          S3_BUCKET: "web.sdk.klleon.io"
        run: |
          aws s3 sync ./apps/js-sdk/dist/ s3://$S3_BUCKET/$VERSION/ --delete --acl public-read
          aws s3 sync ./apps/js-sdk/dist/ s3://$S3_BUCKET/latest/ --delete --acl public-read

      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDE_FRONT_ID: ${{ secrets.AWS_CLOUDE_FRONT_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDE_FRONT_ID --paths "/*"
